spring:
  application:
    name: sk
  datasource:
    url: jdbc:sqlite:./tools/db/data/sk.db
    username: admin
    password: admin
    driverClassName: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.dialect.SQLiteDialect
sk:
  jwt:
    key: 46dcf409d6aafd07cda7a224c1bfba8aa85b66dae9d037984881beef6516118d